/*
 *esta clase es la encaragada de la interfaz GUI 
 */
package appdectmascara;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Luis Alfredo Villera
 */
public class AppDectMascara extends javax.swing.JFrame {

    static Vista_Camara painel;

    public AppDectMascara() {
        initComponents();
        setLocationRelativeTo(null);
        t1 = new Timer(1000, accion);
        this.jMenu_detener.setEnabled(false);
        this.jPanel_Config.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPVista = new javax.swing.JPanel();
        jPanel_Config = new javax.swing.JPanel();
        jSliderVar2 = new javax.swing.JSlider();
        jButton_Guardar_Conf = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        label_Advertencia = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneAdvertecias = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_inicio = new javax.swing.JMenu();
        jMenu_detener = new javax.swing.JMenu();
        jMenu_Cofigurar = new javax.swing.JMenu();
        jMenu_cerrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPVista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPVista.setPreferredSize(new java.awt.Dimension(4, 600));
        jPVista.setRequestFocusEnabled(false);

        jPanel_Config.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSliderVar2.setMajorTickSpacing(3);
        jSliderVar2.setMaximum(30);
        jSliderVar2.setPaintLabels(true);
        jSliderVar2.setPaintTicks(true);
        jSliderVar2.setValue(12);

        jButton_Guardar_Conf.setText("Iniciar y Guardar Configuracion ");
        jButton_Guardar_Conf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Guardar_ConfMouseClicked(evt);
            }
        });
        jButton_Guardar_Conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Guardar_ConfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ConfigLayout = new javax.swing.GroupLayout(jPanel_Config);
        jPanel_Config.setLayout(jPanel_ConfigLayout);
        jPanel_ConfigLayout.setHorizontalGroup(
            jPanel_ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSliderVar2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ConfigLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_Guardar_Conf)
                .addGap(34, 34, 34))
        );
        jPanel_ConfigLayout.setVerticalGroup(
            jPanel_ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSliderVar2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton_Guardar_Conf)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPVistaLayout = new javax.swing.GroupLayout(jPVista);
        jPVista.setLayout(jPVistaLayout);
        jPVistaLayout.setHorizontalGroup(
            jPVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVistaLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jPanel_Config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPVistaLayout.setVerticalGroup(
            jPVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );

        label_Advertencia.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        label_Advertencia.setText("ADVERTENCIAS");
        label_Advertencia.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextPaneAdvertecias.setEditable(false);
        jTextPaneAdvertecias.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(jTextPaneAdvertecias);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(label_Advertencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(label_Advertencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPVista, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPVista, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu_inicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu_inicio.setText("Iniciar_Deteccion");
        jMenu_inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_inicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_inicio);

        jMenu_detener.setText("Detener_Camara");
        jMenu_detener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_detenerMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_detener);

        jMenu_Cofigurar.setText("Configurar_Sensibilidad");
        jMenu_Cofigurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_CofigurarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_Cofigurar);

        jMenu_cerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu_cerrar.setText("Cerrar");
        jMenu_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_cerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_cerrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static int resultado = 0;
    static int resultadoR = 0;
    static int resultadoO = 0;
    static String AlertaSinT = "";
    private Timer t1;
    private int sec = 0;
    private int con = 0;
    private int esconde = 0;

    private ActionListener accion = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent ae) {
            sec++;

            actualizarjText();

        }

    };

    public void pintar_Alertas(int alertT, int alertR, int alertO) {

       resultado = (alertT);
        resultadoR = (alertR);
        resultadoO = (alertO);
        if ((resultado == 0 && resultadoR >= 1) || (resultado == 0 && resultadoO >= 1)) {
            AlertaSinT = "NO SE LE DETECTA TAPABOCAS A LA PERSONA ";
            con++;
            if (con == 5) {
                Manejo_sonido ms = new Manejo_sonido();
                ms.sonido();
                con = 0;
            }

        } else {
            if (con >= 0 && con <= 5) {
                con--;
            }

            AlertaSinT = "";
        }
        
        if ((resultado >= 1)) {
            AlertaSinT = "TAPABOCAS DETECTADO";
        }
    }
    
    //en caso de que no se lea la camara aparecera este exto en el panel 
    public void alCamara(String al) {
        StyledDocument doc = jTextPaneAdvertecias.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        this.jTextPaneAdvertecias.setText(al);
    }
    

    public void actualizarjText() {
         ///
        StyledDocument doc = jTextPaneAdvertecias.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        ///
        
        this.jTextPaneAdvertecias.setText("");
        String ver = "A los " + sec + " segudos se detectan:   " + resultado + " Tapabocas, " + resultadoR + " Rostros y  " + resultadoO + " ojos \n \n" + AlertaSinT;
        this.jTextPaneAdvertecias.setText(ver);

    }


    private void jMenu_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_inicioMouseClicked
        t1.start();
        this.jMenu_inicio.setEnabled(false);
        this.jMenu_detener.setEnabled(true);
        painel = new Vista_Camara();
        painel.iniciarCamara();
        //painel = new Vista_Camara();
        // painel.iniciarCamara();
        painel.setVisible(true);
        painel.setSize(new Dimension(750, 700));
        this.jPVista.add(painel);
        this.jMenu_Cofigurar.setEnabled(false);

        

    }//GEN-LAST:event_jMenu_inicioMouseClicked

    private void jMenu_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_cerrarMouseClicked

        System.exit(0);

    }//GEN-LAST:event_jMenu_cerrarMouseClicked

    private void jMenu_detenerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_detenerMouseClicked
        //painel = new Vista_Camara();
        this.jMenu_inicio.setEnabled(true);
        this.jMenu_detener.setEnabled(false);
        painel.timer();
        painel.apagarcam();
        t1.stop();
        sec = 0;
        this.jTextPaneAdvertecias.setText("");
        this.jMenu_Cofigurar.setEnabled(true);


    }//GEN-LAST:event_jMenu_detenerMouseClicked

    private void jMenu_CofigurarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_CofigurarMouseClicked
        this.jPanel_Config.setVisible(true);
        this.jMenu_inicio.setEnabled(false);
    }//GEN-LAST:event_jMenu_CofigurarMouseClicked

    private void jButton_Guardar_ConfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Guardar_ConfMouseClicked
       this.jPanel_Config.setVisible(false);
        int var2 = (this.jSliderVar2.getValue());
        Detecta dec = new Detecta();
        dec.CambioValorVariable(var2);
        t1.start();
        this.jMenu_inicio.setEnabled(false);
        this.jMenu_detener.setEnabled(true);
        painel = new Vista_Camara();
        painel.iniciarCamara();
        //painel = new Vista_Camara();
        painel.setVisible(true);
        painel.setSize(new Dimension(750, 700));
        this.jPVista.add(painel);
        this.jMenu_Cofigurar.setEnabled(false);


    }//GEN-LAST:event_jButton_Guardar_ConfMouseClicked

    private void jButton_Guardar_ConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Guardar_ConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Guardar_ConfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppDectMascara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppDectMascara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppDectMascara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppDectMascara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new AppDectMascara().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Guardar_Conf;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Cofigurar;
    private javax.swing.JMenu jMenu_cerrar;
    private javax.swing.JMenu jMenu_detener;
    private javax.swing.JMenu jMenu_inicio;
    private javax.swing.JPanel jPVista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_Config;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSliderVar2;
    private javax.swing.JTextPane jTextPaneAdvertecias;
    private javax.swing.JLabel label_Advertencia;
    // End of variables declaration//GEN-END:variables
}
